# Cyb3rhq App Copyright (C) 2021 Cyb3rhq Inc. (License GPLv2)
version: '3.9'

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'

services:
  exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    <<: *logging
    hostname: 'exporter-kbn-${CYB3RHQ_STACK}'
    networks:
      - wzd-pre
      - mon
    command:
      - '--es.uri=https://admin:${KIBANA_PASSWORD}@cyb3rhq.indexer:9200'
      - '--es.ssl-skip-verify'
      - '--es.all'

  imposter:
    image: outofcoffee/imposter
    hostname: 'imposter-kbn-${CYB3RHQ_STACK}'
    networks:
      - wzd-pre
      - mon
    <<: *logging
    environment:
      - JAVA_OPTS="-Xmx512m -Xss512k -Dfile.encoding=UTF-8 -XX:MaxRAM=800m -XX:MaxRAMPercentage=95 -XX:MinRAMPercentage=60A"
      - MALLOC_ARENA_MAX=1
    volumes:
      - ./config/imposter:/opt/imposter/config

  generator:
    image: cfssl/cfssl
    volumes:
      - wi_certs:/certs/wi
      - wd_certs:/certs/wd
      - wm_certs:/certs/wm
      - ./config/certs:/conf
    entrypoint: /bin/bash
    command: >
      -c '
        export certs=/tmp/certs
        mkdir $$certs
      	cd $$certs

      	echo "Generating CA"
      	cfssl gencert -initca /conf/ca.json | cfssljson -bare ca

      	echo "Generating servers certificates"
      	for i in cyb3rhq.indexer cyb3rhq.dashboard cyb3rhq.manager; do
      		echo "Generating cert for $$i"
      		cat /conf/host.json | \
      		sed "s/HOST/$$i/g" | \
      		cfssl gencert \
      			-ca $$certs/ca.pem \
      			-ca-key $$certs/ca-key.pem \
      			-config /conf/cfssl.json \
      			-profile=server - | \
      		cfssljson -bare $$i
      		openssl pkcs8 -topk8 -inform pem -in $$i-key.pem -outform pem -nocrypt -out $$i.key
      	done

      	echo "Generating clients certificates"
        	for i in admin filebeat; do
        		echo "Generating cert for $$i"
      		cat /conf/host.json | \
      		sed "s/HOST/$$i/g" | \
      		cfssl gencert \
      			-ca $$certs/ca.pem \
      			-ca-key $$certs/ca-key.pem \
      			-config /conf/cfssl.json \
      			-profile=client - | \
      		cfssljson -bare $$i
      		openssl pkcs8 -topk8 -inform pem -in $$i-key.pem -outform pem -nocrypt -out $$i.key
      	done

          echo "Setting up permissions"

          rm /certs/wi/* /certs/wd/* /certs/wm/*

          mv $$certs/cyb3rhq.indexer* /certs/wi
          mv $$certs/admin* /certs/wi
          mv /certs/wi/admin.key /certs/wi/admin-key.pem
          cp $$certs/*ca* /certs/wi

          mv $$certs/cyb3rhq.dashboard* /certs/wd
          cp $$certs/*ca* /certs/wd

          mv $$certs/*.* /certs/wm

          chmod 640 /certs/wi/* /certs/wd/* /certs/wm/*
          chown -R 1000:1000 /certs/*
          ls -alR /certs/

          sleep 30
      '
    healthcheck:
      test: ['CMD-SHELL', '[ -r /certs/wm/cyb3rhq.manager.pem ]']
      interval: 2s
      timeout: 5s
      retries: 10

  filebeat:
    depends_on:
      cyb3rhq.indexer:
        condition: service_healthy
    image: elastic/filebeat:7.10.2
    hostname: filebeat
    user: '0:0'
    networks:
      - wzd-pre
      - mon
    <<: *logging
    entrypoint:
      - '/bin/bash'
    command: >
      -c '
        mkdir -p /etc/filebeat
        echo admin | filebeat keystore add username --stdin --force
        echo SecretPassword| filebeat keystore add password --stdin --force
        curl -so /etc/filebeat/cyb3rhq-template.json https://raw.githubusercontent.com/cyb3rhq/cyb3rhq/4.3/extensions/elasticsearch/7.x/cyb3rhq-template.json
        curl -s https://packages.wazuh.com/4.x/filebeat/cyb3rhq-filebeat-0.4.tar.gz | tar -xvz -C /usr/share/filebeat/module
        # copy filebeat to preserve correct permissions without
        # affecting host filesystem
        cp /tmp/filebeat.yml /usr/share/filebeat/filebeat.yml
        chown root.root /usr/share/filebeat/filebeat.yml
        chmod go-w /usr/share/filebeat/filebeat.yml
        filebeat setup -e
        filebeat
      '
    volumes:
      - wm_certs:/etc/ssl/cyb3rhq
      - ./config/filebeat/filebeat.yml:/tmp/filebeat.yml

  cyb3rhq.indexer:
    depends_on:
      generator:
        condition: service_healthy
    image: cyb3rhq/cyb3rhq-indexer:${CYB3RHQ_STACK}
    hostname: cyb3rhq.indexer
    networks:
      - wzd-pre
      - mon
    <<: *logging
    environment:
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'OPENSEARCH_PATH_CONF=/usr/share/cyb3rhq-indexer/config'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - cyb3rhq-indexer-data:/var/lib/cyb3rhq-indexer
      - wi_certs:/usr/share/cyb3rhq-indexer/config/certs/
      - ./config/cyb3rhq_indexer/cyb3rhq.indexer.yml:/usr/share/cyb3rhq-indexer/config/opensearch.yml
      - ./config/cyb3rhq_indexer/internal_users.yml:/usr/share/cyb3rhq-indexer/plugins/opensearch-security/securityconfig/internal_users.yml
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/usr/share/cyb3rhq-indexer/bin/opensearch-plugin list | grep -q security',
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  cyb3rhq.dashboard:
    image: cyb3rhq/cyb3rhq-dashboard:${CYB3RHQ_STACK}
    hostname: cyb3rhq.dashboard
    depends_on:
      cyb3rhq.indexer:
        condition: service_healthy
    networks:
      - wzd-pre
      - mon
    <<: *logging
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - CYB3RHQ_API_URL=http://imposter:8080
      - API_USERNAME=cyb3rhq-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - wd_certs:/usr/share/cyb3rhq-dashboard/certs
      - ./config/cyb3rhq_dashboard/cyb3rhq_dashboards.yml:/usr/share/cyb3rhq-dashboard/config/cyb3rhq_dashboards.yml
      - ./config/cyb3rhq_dashboard/cyb3rhq.yml:/usr/share/cyb3rhq-dashboard/data/cyb3rhq/config/cyb3rhq.yml

networks:
  networks:
  wzd-pre:
    name: wzd-pre-${CYB3RHQ_STACK}
    driver: bridge
  mon:
    external: true

volumes:
  cyb3rhq-indexer-data:
  wi_certs:
  wd_certs:
  wm_certs:
