
# Cyb3rhq - Filebeat configuration file
filebeat.modules:
  - module: cyb3rhq
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/cyb3rhq-template.json'
setup.template.json.name: 'cyb3rhq'
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://cyb3rhq.indexer:9200']
  username: 'admin'
  password: 'SecretPassword'
  ssl.verification_mode: full
  ssl.certificate_authorities: ['/etc/ssl/cyb3rhq/ca.pem']
  ssl.certificate: '/etc/ssl/cyb3rhq/filebeat.pem'
  ssl.key: '/etc/ssl/cyb3rhq/filebeat-key.pem'
