# This is a basic workflow that is manually triggered
# @deprecated Official Cyb3rhq images must be used instead: https://hub.docker.com/r/cyb3rhq/cyb3rhq

name: Manual workflow build and push docker image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      build-manager-image:
        type: boolean
        description: 'Build manager image'
        required: false
      cyb3rhq-manager-version:
        description: 'Cyb3rhq manager version'
        default: 'v4.3.8'
        required: false
      elastic-manager-version:
        description: 'Elastic manager version'
        default: '7.17.0'
        required: false

      build-agent-image:
        type: boolean
        description: 'Build agent image'
        required: false
      cyb3rhq-agent-version:
        description: 'Cyb3rhq agent version'
        default: 'v4.3.8'
        required: false
      elastic-agent-version:
        description: 'Elastic manager version'
        default: '7.17.0'
        required: false

      build-cypress-image:
        type: boolean
        description: 'Build cypress image'
        required: false
      ubuntu-cypress-branch:
        description: 'Ubuntu cypress branch: Branch in which the image will be created, this branch must correspond to the cyb3rhq-kibana-app project. It will take the tests written in the cyb3rhq-kibana-app/test/cypress directory.'
        default: 'main'
        required: false
      image-cypress-version:
        description: 'Image cypress version'
        default: '3.0.0'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-build-manager-image:
    if: ${{ github.event.inputs.build-manager-image == 'true' }}
    name: Run build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: Step 01 - Download cyb3rhq-kibana-app
        uses: actions/checkout@v2
        with:
          path: cyb3rhq-kibana-app
      - name: Step 02 - Login to quay.io
        run: |
          docker login -u=${{ secrets.QUAYIO_USERNAME }} -p=${{ secrets.QUAYIO_TOKEN }} quay.io
      - name: Step 03 - Build image
        run: |
          cd ${{ github.workspace }}/cyb3rhq-kibana-app/test/cypress/images/cyb3rhq_manager_filebeat_sources_cmake
          docker build -t quay.io/cyb3rhq/cyb3rhq-manager-image:${{ github.event.inputs.cyb3rhq-manager-version }}-${{ github.event.inputs.elastic-manager-version }} \
          --build-arg CYB3RHQ_VERSION=${{ github.event.inputs.cyb3rhq-manager-version }} \
          --build-arg FILEBEAT_VERSION=${{ github.event.inputs.elastic-manager-version }} \
          --build-arg FILEBEAT_CYB3RHQ_TEMPLATE_URL=https://raw.githubusercontent.com/cyb3rhq/cyb3rhq/4.0/extensions/elasticsearch/7.x/cyb3rhq-template.json \
          --build-arg FILEBEAT_CYB3RHQ_MODULE_URL=https://packages.wazuh.com/4.x/filebeat/cyb3rhq-filebeat-0.4.tar.gz .
      - name: Step 04 - Push image to quay.io
        run: |
          docker push quay.io/cyb3rhq/cyb3rhq-manager-image:${{ github.event.inputs.cyb3rhq-manager-version }}-${{ github.event.inputs.elastic-manager-version }}

  job-build-agent-image:
    if: ${{ github.event.inputs.build-agent-image == 'true' }}
    name: Run build and push agent image
    runs-on: ubuntu-latest
    steps:
      - name: Step 01 - Download cyb3rhq-kibana-app
        uses: actions/checkout@v2
        with:
          path: cyb3rhq-kibana-app
      - name: Step 02 - Login to quay.io
        run: |
          docker login -u=${{ secrets.QUAYIO_USERNAME }} -p=${{ secrets.QUAYIO_TOKEN }} quay.io
      - name: Step 03 - Build image
        run: |
          cd ${{ github.workspace }}/cyb3rhq-kibana-app/test/cypress/images/cyb3rhq_agent_ubuntu_sources_cmake
          docker build -t quay.io/cyb3rhq/cyb3rhq-agent-image:${{ github.event.inputs.cyb3rhq-agent-version }} \
          --build-arg CYB3RHQ_VERSION=${{ github.event.inputs.cyb3rhq-agent-version }} .
      - name: Step 04 - Push image to quay.io
        run: |
          docker push quay.io/cyb3rhq/cyb3rhq-agent-image:${{ github.event.inputs.cyb3rhq-agent-version }}

  job-build-cypress-image:
    if: ${{ github.event.inputs.build-cypress-image == 'true' }}
    name: Run build and push cypress image
    runs-on: ubuntu-latest
    steps:
      - name: Step 01 - Download cyb3rhq-kibana-app
        uses: actions/checkout@v2
        with:
          path: cyb3rhq-kibana-app
      - name: Step 02 - Login to quay.io
        run: |
          docker login -u=${{ secrets.QUAYIO_USERNAME }} -p=${{ secrets.QUAYIO_TOKEN }} quay.io
      - name: Step 03 - Build image
        run: |
          cd ${{ github.workspace }}/cyb3rhq-kibana-app/test/cypress/images/ubuntu-cypress
          docker build -t quay.io/cyb3rhq/cyb3rhq-ubuntu-cypress:${{ github.event.inputs.image-cypress-version }} \
          --build-arg UBUNTU_CYPRESS_BRANCH=${{ github.event.inputs.ubuntu-cypress-branch }} .
      - name: Step 04 - Push image to quay.io
        run: |
          docker push quay.io/cyb3rhq/cyb3rhq-ubuntu-cypress:${{ github.event.inputs.image-cypress-version }}
